repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2  # Check for latest version
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        exclude: "alembic/|app/model/__init__.py"