"""Add lock connection

Revision ID: cedc638ba0d2
Revises: a47ec0987478
Create Date: 2025-03-30 13:12:47.327193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedc638ba0d2'
down_revision: Union[str, None] = 'a47ec0987478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_connection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'conversation_id')
    )
    op.drop_index('ix_conversation_id', table_name='conversation')
    op.drop_index('ix_message_id', table_name='message')
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_message_id', 'message', ['id'], unique=False)
    op.create_index('ix_conversation_id', 'conversation', ['id'], unique=False)
    op.drop_table('websocket_connection')
    # ### end Alembic commands ###
